# /home/thinh/WorkSpace/ecommerce-ts/docker-compose.yml
# http://192.168.1.8:8081/
# docker network create ecommerce-net

services:
  mongodb:
    image: mongo:7
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEV_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce-net

  mongo-express:
    image: mongo-express:latest
    container_name: ecommerce-mongo-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DEV_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DEV_DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: william
      ME_CONFIG_BASICAUTH_PASSWORD: william123
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongodb
    networks:
      - ecommerce-net

volumes:
  mongo_data:

networks:
  ecommerce-net:
    external: true