# ecommerce-ts/docker/docker-compose.kafka.yml

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: ecommerce-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"     # internal docker traffic (optional but fine)
      - "19092:9094"    # host -> kafka external
    environment:
      # === KRaft ===
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@ecommerce-kafka:9093

      # === Listeners ===
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://ecommerce-kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # === Single node ===
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ecommerce-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ecommerce-kafka-ui
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ecommerce
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ecommerce-kafka:9092
    depends_on:
      - kafka
    networks:
      - ecommerce-net

volumes:
  kafka_data:

networks:
  ecommerce-net:
    external: true